export const pages = [
  [
    "C08",
    "演示中心",
    "/guide",
    "公共",
    "guide",
    "Presentation",
    "先选演示路线，再按角色、操作和预期结果逐步展示",
  ],
  [
    "C01",
    "工作台",
    "/workbench",
    "公共",
    "overview",
    "LayoutDashboard",
    "一处掌握任务、训练与演练的完整进展",
  ],
  [
    "C02",
    "资源中心",
    "/assets",
    "公共",
    "assets",
    "Boxes",
    "统一管理模型、场景与课件资源",
  ],
  [
    "C03",
    "场景编辑器",
    "/editor/:id",
    "公共",
    "authoring",
    "PanelsTopLeft",
    "组织场景对象，配置行为与交互",
  ],
  [
    "C04",
    "发布中心",
    "/releases",
    "公共",
    "authoring",
    "Send",
    "审核、构建与发布每一个可追溯版本",
  ],
  [
    "C05",
    "训练运行",
    "/sessions/:id",
    "公共",
    "training",
    "Play",
    "让每一次操作都有过程、有反馈、有记录",
  ],
  [
    "C06",
    "记录与报告",
    "/records/:id",
    "公共",
    "records",
    "FileChartColumn",
    "从结果回到原始事件与业务证据",
  ],
  [
    "C07",
    "演示管理",
    "/demo",
    "公共",
    "settings",
    "Settings2",
    "管理独立工作区、演示数据与平台能力",
  ],
  [
    "S101",
    "素材工程",
    "/operation/projects",
    "操作训练",
    "authoring",
    "FolderKanban",
    "从单设备素材到可复用的系统课程",
  ],
  [
    "S102",
    "设备组网",
    "/operation/topologies/:id",
    "操作训练",
    "authoring",
    "Network",
    "配置四设备信号与联动条件",
  ],
  [
    "S103",
    "系统模板",
    "/operation/templates",
    "操作训练",
    "authoring",
    "Copy",
    "沉淀系统配置，复用成熟训练内容",
  ],
  [
    "S104",
    "操作课程",
    "/operation/courses/:id",
    "操作训练",
    "authoring",
    "BookOpen",
    "编排课程步骤、模式与交互规则",
  ],
  [
    "S105",
    "台位与外设",
    "/operation/stations",
    "操作训练",
    "authoring",
    "Monitor",
    "配置模拟台位与输入信号映射",
  ],
  [
    "S106",
    "训练资源归档",
    "/operation/library",
    "操作训练",
    "records",
    "Archive",
    "检索课程版本与操作训练记录",
  ],
  [
    "S201",
    "维修场景",
    "/maintenance/scenes",
    "维修培训",
    "authoring",
    "Wrench",
    "构建装备、工具和维修交互场景",
  ],
  [
    "S202",
    "维修课件",
    "/maintenance/courses/:id",
    "维修培训",
    "authoring",
    "BookOpenCheck",
    "将维修需求转为可执行的培训课件",
  ],
  [
    "S203",
    "培训任务",
    "/maintenance/assignments",
    "维修培训",
    "training",
    "Users",
    "组织培训并确认本次训练证据",
  ],
  [
    "S204",
    "培训评价",
    "/maintenance/evaluations",
    "维修培训",
    "training",
    "GraduationCap",
    "查看过程成绩、问卷与改进反馈",
  ],
  [
    "S301",
    "保障任务",
    "/support/tasks/:id",
    "保障筹划",
    "planning",
    "ClipboardList",
    "定义任务范围、对象与工序目标",
  ],
  [
    "S302",
    "履历与资料",
    "/support/equipment/:id",
    "保障筹划",
    "planning",
    "Files",
    "贯通履历、构型、技术资料与需求分析",
  ],
  [
    "S303",
    "保障资源",
    "/support/resources",
    "保障筹划",
    "planning",
    "Container",
    "统一建模人员、物料、器材与设施",
  ],
  [
    "S304",
    "寿期与多任务",
    "/support/planning",
    "保障筹划",
    "planning",
    "CalendarRange",
    "比较维修周期、任务排序与资源约束",
  ],
  [
    "S305",
    "预案库",
    "/support/plans",
    "保障筹划",
    "planning",
    "Library",
    "匹配模板，复用已发布的保障预案",
  ],
  [
    "S306",
    "预案编制",
    "/support/plans/:id",
    "保障筹划",
    "planning",
    "GanttChart",
    "编制工序、配置资源并计算真实排程",
  ],
  [
    "S307",
    "生产前准备",
    "/support/preparations/:id",
    "保障筹划",
    "planning",
    "ListChecks",
    "让六类准备清单落到具体责任和单据",
  ],
  [
    "S308",
    "专项计划",
    "/support/subplans/:id",
    "保障筹划",
    "planning",
    "NotebookTabs",
    "编制施工、采购、仓储、调试与试验计划",
  ],
  [
    "S309",
    "重点工程规划",
    "/support/special-plans/:id",
    "保障筹划",
    "planning",
    "Route",
    "比较维修方案与模拟出舱路径",
  ],
  [
    "S310",
    "导调配置",
    "/support/directives/:id",
    "保障演练",
    "exercise",
    "SlidersHorizontal",
    "配置场景、预案与导调事件",
  ],
  [
    "S311",
    "演练监控",
    "/support/exercises/:id",
    "保障演练",
    "exercise",
    "Radar",
    "同步观察任务、资源、时间与事件",
  ],
  [
    "S312",
    "指标评估",
    "/support/evaluations/:id",
    "保障演练",
    "analysis",
    "ChartNoAxesCombined",
    "配置指标，查看计算过程和来源",
  ],
  [
    "S313",
    "敏感性分析",
    "/support/sensitivity/:id",
    "保障演练",
    "analysis",
    "ChartSpline",
    "查看到货与资源变化对方案的影响",
  ],
  [
    "S314",
    "模拟施工",
    "/support/executions/:id",
    "执行归档",
    "execution",
    "HardHat",
    "从签收、报工到检查与整改闭环",
  ],
  [
    "S315",
    "对比与改进",
    "/support/comparisons/:id",
    "执行归档",
    "analysis",
    "GitCompareArrows",
    "对比预计与实绩，形成下一版改进",
  ],
  [
    "S316",
    "成果归档",
    "/support/archives/:id",
    "执行归档",
    "records",
    "FolderCheck",
    "三级审核、成果发布与再次复用",
  ],
].map(([id, title, path, group, view, icon, description]) => ({
  id,
  title,
  path,
  group,
  view,
  icon,
  description,
}));
export const pathFor = (id: string, target = "current") =>
  pages.find((p) => p.id === id)!.path.replace(":id", target);
export const statusText: Record<string, string> = {
  DRAFT: "草稿",
  PROCESSING: "处理中",
  PENDING_REVIEW: "待审核",
  APPROVED: "已批准",
  PUBLISHED: "已发布",
  BUILDING: "构建中",
  BUILD_FAILED: "构建失败",
  DISABLED: "已停用",
  READY: "准备就绪",
  RUNNING: "进行中",
  PAUSED: "已暂停",
  COMPLETED: "已完成",
  ASSIGNED: "待开始",
  PENDING: "待接收",
  ACCEPTED: "已验收",
  ISSUED: "待签收",
  ACKNOWLEDGED: "已签收",
  PENDING_INSPECTION: "待检查",
  RECTIFICATION_REQUIRED: "待整改",
  PENDING_RECHECK: "待复查",
  READY_HANDOVER: "待交接",
  RETURNED: "已退回",
  SUBMITTED: "一级待审",
  L1_APPROVED: "二级待审",
  L2_APPROVED: "三级待审",
  L3_APPROVED: "待发布",
  DISPATCHED: "在途",
  RECEIVED: "已入库",
  CLOSED: "已关闭",
  SUCCEEDED: "已成功",
  FAILED: "失败",
  CONNECTED: "已连接",
  DISCONNECTED: "未连接",
  OPEN: "待处理",
  FIX_SUBMITTED: "已提交整改",
  PLANNED: "已建预案",
  CONFIRMED: "已确认",
  EVALUATED: "已评估",
  ADOPTED: "已采纳",
  ALARM: "状态异常",
  STOPPED: "已停止",
};
export const actionText: Record<string, string> = {
  "course.create": "创建课程",
  "course.submit": "提交课程审核",
  "course.approve": "审核课程",
  "course.publish": "发布课程",
  "training.action": "提交训练操作",
  "training.confirm": "确认培训证据",
  "task.create": "创建保障任务",
  "plan.create": "创建预案",
  "plan.approve": "批准预案",
  "run.create": "创建演练",
  "run.step": "推进演练",
  "run.finish": "完成演练",
  "run.inject": "导调干预",
  "execution.report": "提交模拟实绩",
  "inspection.submit": "提交检查结论",
  "archive.submit": "提交成果审核",
  "archive.supplement": "补充成果说明",
  "archive.review": "成果审核",
  "archive.publish": "成果发布",
  "workspace.reset": "重置工作区",
};
