import type { SystemId } from "./domain";

export type PageMeta = {
  id: string;
  title: string;
  path: string;
  system: SystemId | null;
  feature: string;
  view: string;
  scope: "PUBLIC" | "SYSTEM";
  section: string;
  icon: string;
  description: string;
  sidebar?: boolean;
};

const page = (
  id: string,
  title: string,
  path: string,
  system: SystemId | null,
  feature: string,
  view: string,
  section: string,
  icon: string,
  description: string,
  sidebar = true,
): PageMeta => ({
  id,
  title,
  path,
  system,
  feature,
  view,
  scope: system ? "SYSTEM" : "PUBLIC",
  section,
  icon,
  description,
  sidebar,
});

export const pages: PageMeta[] = [
  page(
    "C08",
    "演示中心",
    "/guide",
    null,
    "guide",
    "guide",
    "工作空间",
    "Presentation",
    "先选演示路线，再按角色、操作和预期结果逐步展示",
  ),
  page(
    "C01",
    "工作台",
    "/workbench",
    null,
    "overview",
    "overview",
    "工作空间",
    "LayoutDashboard",
    "一处掌握任务、训练与演练的完整进展",
  ),
  page(
    "C02",
    "资源中心",
    "/assets",
    null,
    "assets",
    "assets",
    "工作空间",
    "Boxes",
    "统一管理模型、场景与课件资源",
  ),
  page(
    "C03",
    "场景编辑器",
    "/editor/:id",
    null,
    "legacy-editor",
    "authoring",
    "公共服务",
    "PanelsTopLeft",
    "兼容旧场景编辑入口",
    false,
  ),
  page(
    "C04",
    "发布中心",
    "/releases",
    null,
    "releases",
    "authoring",
    "公共服务",
    "Send",
    "审核、构建与发布每一个可追溯版本",
  ),
  page(
    "C05",
    "训练运行",
    "/sessions/:id",
    null,
    "session",
    "training",
    "公共服务",
    "Play",
    "按训练记录所属系统显示过程、反馈和返回入口",
    false,
  ),
  page(
    "C06",
    "全部系统记录",
    "/records/:id",
    null,
    "records",
    "records",
    "公共服务",
    "FileChartColumn",
    "跨系统查看结果、原始事件与业务证据",
  ),
  page(
    "C07",
    "演示管理",
    "/demo",
    null,
    "settings",
    "settings",
    "公共服务",
    "Settings2",
    "管理独立工作区、演示数据与平台能力",
  ),

  page(
    "OP01",
    "系统工作台",
    "/operation/overview",
    "OPERATION",
    "overview",
    "system-overview",
    "本系统工作台",
    "LayoutDashboard",
    "查看本系统课件、任务、训练和归档进展",
  ),
  page(
    "S101",
    "素材工程",
    "/operation/projects",
    "OPERATION",
    "projects",
    "authoring",
    "资源准备",
    "FolderKanban",
    "从单设备素材到可复用的系统课程",
  ),
  page(
    "S102",
    "设备组网",
    "/operation/topologies/:id",
    "OPERATION",
    "topologies",
    "authoring",
    "资源准备",
    "Network",
    "配置四设备信号与联动条件",
  ),
  page(
    "S103",
    "系统模板",
    "/operation/templates",
    "OPERATION",
    "templates",
    "authoring",
    "资源准备",
    "Copy",
    "沉淀系统配置，复用成熟训练内容",
  ),
  page(
    "S104",
    "操作课件",
    "/operation/coursewares/:id",
    "OPERATION",
    "coursewares",
    "authoring",
    "教学制作",
    "BookOpen",
    "编排操作课件步骤、模式与交互规则",
  ),
  page(
    "S105",
    "台位与外设",
    "/operation/stations",
    "OPERATION",
    "stations",
    "authoring",
    "培训组织",
    "Monitor",
    "配置模拟台位与输入信号映射",
  ),
  page(
    "O106",
    "培训任务",
    "/operation/assignments",
    "OPERATION",
    "assignments",
    "training",
    "培训组织",
    "Users",
    "只查看和处理装备使用及作战运用培训任务",
  ),
  page(
    "O107",
    "培训评价",
    "/operation/training-evaluations",
    "OPERATION",
    "training-evaluations",
    "training",
    "训练评价",
    "GraduationCap",
    "查看本系统训练成绩、问卷和证据确认",
  ),
  page(
    "S106",
    "训练归档",
    "/operation/training-records",
    "OPERATION",
    "training-records",
    "records",
    "训练评价",
    "Archive",
    "检索本系统课件版本和操作训练记录",
  ),

  page(
    "M001",
    "系统工作台",
    "/maintenance/overview",
    "MAINTENANCE",
    "overview",
    "system-overview",
    "本系统工作台",
    "LayoutDashboard",
    "查看本系统课件、任务、训练和归档进展",
  ),
  page(
    "S201",
    "维修场景",
    "/maintenance/scenes",
    "MAINTENANCE",
    "scenes",
    "authoring",
    "资源准备",
    "Wrench",
    "构建装备、工具和维修交互场景",
  ),
  page(
    "S202",
    "维修课件",
    "/maintenance/coursewares/:id",
    "MAINTENANCE",
    "coursewares",
    "authoring",
    "教学制作",
    "BookOpenCheck",
    "将维修需求转为可执行的培训课件",
  ),
  page(
    "S203",
    "培训任务",
    "/maintenance/assignments",
    "MAINTENANCE",
    "assignments",
    "training",
    "培训组织",
    "Users",
    "只查看和处理装备维修保障培训任务",
  ),
  page(
    "S204",
    "培训评价",
    "/maintenance/training-evaluations",
    "MAINTENANCE",
    "training-evaluations",
    "training",
    "训练评价",
    "GraduationCap",
    "查看本系统训练成绩、问卷和证据确认",
  ),
  page(
    "M006",
    "训练归档",
    "/maintenance/training-records",
    "MAINTENANCE",
    "training-records",
    "records",
    "训练评价",
    "Archive",
    "检索本系统维修培训记录和历史版本",
  ),

  page(
    "U001",
    "系统工作台",
    "/support/overview",
    "SUPPORT",
    "overview",
    "system-overview",
    "本系统工作台",
    "LayoutDashboard",
    "查看保障任务、预案、演练和成果归档进展",
  ),
  page(
    "U002",
    "教学训练",
    "/support/training",
    "SUPPORT",
    "training-scope",
    "training",
    "教学训练",
    "BookOpenCheck",
    "查看保障教学训练的阶段范围和后续建设边界",
  ),
  page(
    "S301",
    "保障任务",
    "/support/tasks/:id",
    "SUPPORT",
    "tasks",
    "planning",
    "保障筹划",
    "ClipboardList",
    "定义任务范围、对象与工序目标",
  ),
  page(
    "S302",
    "履历与资料",
    "/support/equipment/:id",
    "SUPPORT",
    "equipment",
    "planning",
    "保障筹划",
    "Files",
    "贯通履历、构型、技术资料与需求分析",
  ),
  page(
    "S303",
    "保障资源",
    "/support/resources",
    "SUPPORT",
    "resources",
    "planning",
    "保障筹划",
    "Container",
    "统一建模人员、物料、器材与设施",
  ),
  page(
    "S304",
    "寿期与多任务",
    "/support/planning",
    "SUPPORT",
    "lifecycle",
    "planning",
    "保障筹划",
    "CalendarRange",
    "比较维修周期、任务排序与资源约束",
  ),
  page(
    "S305",
    "预案库",
    "/support/plans",
    "SUPPORT",
    "plan-library",
    "planning",
    "保障筹划",
    "Library",
    "匹配模板，复用已发布的保障预案",
  ),
  page(
    "S306",
    "预案编制",
    "/support/plans/:id",
    "SUPPORT",
    "plans",
    "planning",
    "保障筹划",
    "GanttChart",
    "编制工序、配置资源并计算真实排程",
  ),
  page(
    "S307",
    "生产前准备",
    "/support/preparations/:id",
    "SUPPORT",
    "preparations",
    "planning",
    "保障筹划",
    "ListChecks",
    "让六类准备清单落到具体责任和单据",
  ),
  page(
    "S308",
    "专项计划",
    "/support/subplans/:id",
    "SUPPORT",
    "subplans",
    "planning",
    "保障筹划",
    "NotebookTabs",
    "编制施工、采购、仓储、调试与试验计划",
  ),
  page(
    "S309",
    "重点工程规划",
    "/support/special-plans/:id",
    "SUPPORT",
    "special-plans",
    "planning",
    "保障筹划",
    "Route",
    "比较维修方案与模拟出舱路径",
  ),
  page(
    "S310",
    "导调配置",
    "/support/directives/:id",
    "SUPPORT",
    "directives",
    "exercise",
    "保障演练",
    "SlidersHorizontal",
    "配置场景、预案与导调事件",
  ),
  page(
    "S311",
    "演练监控",
    "/support/exercises/:id",
    "SUPPORT",
    "exercises",
    "exercise",
    "保障演练",
    "Radar",
    "同步观察任务、资源、时间与事件",
  ),
  page(
    "S312",
    "指标评估",
    "/support/evaluations/:id",
    "SUPPORT",
    "evaluations",
    "analysis",
    "保障演练",
    "ChartNoAxesCombined",
    "配置指标，查看计算过程和来源",
  ),
  page(
    "S313",
    "敏感性分析",
    "/support/sensitivity/:id",
    "SUPPORT",
    "sensitivity",
    "analysis",
    "保障演练",
    "ChartSpline",
    "查看到货与资源变化对方案的影响",
  ),
  page(
    "S314",
    "模拟施工",
    "/support/executions/:id",
    "SUPPORT",
    "executions",
    "execution",
    "执行归档",
    "HardHat",
    "从签收、报工到检查与整改闭环",
  ),
  page(
    "S315",
    "对比与改进",
    "/support/comparisons/:id",
    "SUPPORT",
    "comparisons",
    "analysis",
    "执行归档",
    "GitCompareArrows",
    "对比预计与实绩，形成下一版改进",
  ),
  page(
    "S316",
    "成果归档",
    "/support/archives/:id",
    "SUPPORT",
    "archives",
    "records",
    "执行归档",
    "FolderCheck",
    "三级审核、成果发布与再次复用",
  ),
];

export const publicNavIds = ["C01", "C08", "C02"];
export const publicServiceIds = ["C04", "C06", "C07"];

export const legacyRoutes = [
  { path: "/operation/courses/:id", targetId: "S104" },
  { path: "/maintenance/courses/:id", targetId: "S202" },
  { path: "/maintenance/evaluations", targetId: "S204" },
  { path: "/operation/library", targetId: "S106" },
];

export const pathFor = (id: string, target = "current") => {
  const found = pages.find((p) => p.id === id);
  if (!found) return "/not-found";
  return found.path.replace(":id", target);
};

export const pathForFeature = (
  system: SystemId,
  feature: string,
  target = "current",
) => {
  const found = pages.find((p) => p.system === system && p.feature === feature);
  return found ? found.path.replace(":id", target) : "/not-found";
};

export const statusText: Record<string, string> = {
  DRAFT: "草稿",
  PROCESSING: "处理中",
  PENDING_REVIEW: "待审核",
  APPROVED: "已批准",
  PUBLISHED: "已发布",
  BUILDING: "构建中",
  BUILD_FAILED: "构建失败",
  DISABLED: "已停用",
  READY: "准备就绪",
  RUNNING: "进行中",
  PAUSED: "已暂停",
  COMPLETED: "已完成",
  ASSIGNED: "待开始",
  PENDING: "待接收",
  ACCEPTED: "已验收",
  ISSUED: "待签收",
  ACKNOWLEDGED: "已签收",
  PENDING_INSPECTION: "待检查",
  RECTIFICATION_REQUIRED: "待整改",
  PENDING_RECHECK: "待复查",
  READY_HANDOVER: "待交接",
  RETURNED: "已退回",
  SUBMITTED: "一级待审",
  L1_APPROVED: "二级待审",
  L2_APPROVED: "三级待审",
  L3_APPROVED: "待发布",
  DISPATCHED: "在途",
  RECEIVED: "已入库",
  CLOSED: "已关闭",
  SUCCEEDED: "已成功",
  FAILED: "失败",
  CONNECTED: "已连接",
  DISCONNECTED: "未连接",
  OPEN: "待处理",
  FIX_SUBMITTED: "已提交整改",
  PLANNED: "已建预案",
  CONFIRMED: "已确认",
  EVALUATED: "已评估",
  ADOPTED: "已采纳",
  ALARM: "状态异常",
  STOPPED: "已停止",
};

export const actionText: Record<string, string> = {
  "course.create": "创建课程",
  "course.submit": "提交课程审核",
  "course.approve": "审核课程",
  "course.publish": "发布课程",
  "training.action": "提交训练操作",
  "training.confirm": "确认培训证据",
  "task.create": "创建保障任务",
  "plan.create": "创建预案",
  "plan.approve": "批准预案",
  "run.create": "创建演练",
  "run.step": "推进演练",
  "run.finish": "完成演练",
  "run.inject": "导调干预",
  "execution.report": "提交模拟实绩",
  "inspection.submit": "提交检查结论",
  "archive.submit": "提交成果审核",
  "archive.supplement": "补充成果说明",
  "archive.review": "成果审核",
  "archive.publish": "成果发布",
  "workspace.reset": "重置工作区",
};
